Support cargo 1.46.0 ref not found message
In cargo 1.45.0 the message we were matching against was:

```
    Updating crates.io index
    Updating git repository `https://github.com/BurntSushi/utf8-ranges`
error: failed to get `utf8-ranges` as a dependency of package `dependabot v0.1.0 (/home/dependabot/dependabot-core/cargo/tmp/dependabot_20200902-3407-1pi6vdm)`

Caused by:
  failed to load source for dependency `utf8-ranges`

Caused by:
  Unable to update https://github.com/BurntSushi/utf8-ranges#11111b37

Caused by:
  revspec '11111b376b93484341c68fbca3ca110ae5cd2708' not found; class=Reference (4); code=NotFound (-3)
```

In cargo 1.46.0 this has been changed to:

```
    Updating crates.io index
    Updating git repository `https://github.com/BurntSushi/utf8-ranges`
error: failed to get `utf8-ranges` as a dependency of package `dependabot v0.1.0 (/home/dependabot/dependabot-core/cargo/tmp/dependabot_20200902-15-ij9hoa)`

Caused by:
  failed to load source for dependency `utf8-ranges`

Caused by:
  Unable to update https://github.com/BurntSushi/utf8-ranges#11111b37

Caused by:
  object not found - no match for id (11111b376b93484341c68fbca3ca110ae5cd2708); class=Odb (9); code=NotFound (-3)
```

This change matches against both messages, and ensures we raise a
`GitDependencyReferenceNotFound` as expected.